POST http://localhost:4321/entries
Content-Type: application/json

{
//  "date": "2026-01-03",
  "running": {
    "schedule": "adhoc",
    "trackId": "nuselak",
    "progress": "full",
    "performance": 3
  },
  "workout": {
    "schedule": "regular",
    "routine": "monday",
    "results": [
      {
        "exercise": "squats",
        "reps": "24+24+28"
      },
      {
        "exercise": "kneePushUps",
        "reps": "10+10+8"
      },
      {
        "exercise": "frontPlank",
        "holds": "55s"
      },
      {
        "exercise": "ringsHold",
        "holds": "20s"
      },
      {
        "exercise": "barHang",
        "holds": "30s"
      }
    ]
  }
//  "weight": null,
//  "lastMeal": null,
}

### 

POST http://localhost:4321/tracks
Content-Type: application/json

{
  "id": "nuselak",
  "name": "Nuselák",
  "length": 1.5,
  "url": "https://mapy.com/s/kasejadole",
  "progressUnit": "km"
}
